// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7VWC1MLF0xHVd8hCFzsga30RAmGwK6Vo',
    appId: '1:545024822258:web:0b6f9f015601678ef1b96b',
    messagingSenderId: '545024822258',
    projectId: 'synergy-share-exchange-network',
    authDomain: 'synergy-share-exchange-network.firebaseapp.com',
    storageBucket: 'synergy-share-exchange-network.appspot.com',
    measurementId: 'G-Y66C9QWRJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB32s0oI9Xvg2F9Iibtw2IN7LC7NZC4-pY',
    appId: '1:545024822258:android:99c90d4caf7afd81f1b96b',
    messagingSenderId: '545024822258',
    projectId: 'synergy-share-exchange-network',
    storageBucket: 'synergy-share-exchange-network.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjPah7cj1dbZ5wYn_6OdFDsZhbyMLJiQk',
    appId: '1:545024822258:ios:8dcada66fe779fe7f1b96b',
    messagingSenderId: '545024822258',
    projectId: 'synergy-share-exchange-network',
    storageBucket: 'synergy-share-exchange-network.appspot.com',
    iosBundleId: 'com.example.ssenUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjPah7cj1dbZ5wYn_6OdFDsZhbyMLJiQk',
    appId: '1:545024822258:ios:8dcada66fe779fe7f1b96b',
    messagingSenderId: '545024822258',
    projectId: 'synergy-share-exchange-network',
    storageBucket: 'synergy-share-exchange-network.appspot.com',
    iosBundleId: 'com.example.ssenUser',
  );
}
